# Generated by Django 3.2.6 on 2021-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
