# Generated by Django 3.2.6 on 2021-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_descripation',
            field=models.TextField(null=True),
        ),
    ]
